import type { Metadata } from "next";
import React, { Suspense } from "react";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { cookies } from "next/headers";
import { ColorModeContextProvider } from "@contexts/color-mode";
import { Refine } from "@refinedev/core";
import routerProvider from "@refinedev/nextjs-router";
import { dataProviderApp, authProvider, accessControlProvider } from "@providers";
import { useNotificationProvider } from "@refinedev/antd";
import { resources } from "@resources";
import { Provider } from "jotai";
import { appStore } from "@stores";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");

  return (
    <html lang="en">
      <body>
        <Suspense>
          <AntdRegistry>
            <ColorModeContextProvider defaultMode={theme?.value}>
              <Refine
                routerProvider={routerProvider}
                dataProvider={dataProviderApp}
                notificationProvider={useNotificationProvider}
                accessControlProvider={accessControlProvider}
                authProvider={authProvider}
                resources={resources}
                options={{
                  syncWithLocation: true,
                  warnWhenUnsavedChanges: true,
                  useNewQueryKeys: true,
                  projectId: "JapdgP-Ptd9DO-0zi81P",
                }}
              >
                {children}
              </Refine>
            </ColorModeContextProvider>
          </AntdRegistry>
        </Suspense>
      </body>
    </html>
  );
}